#!/bin/bash

# Collect and compile schemas for gnome-shell extensions
# https://askubuntu.com/a/491224

set -e

touch /usr/share/glib-2.0/schemas  # am I root?

REPO=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
find $REPO -name *.gschema.xml -exec cp -v {} /usr/share/glib-2.0/schemas/ \;
glib-compile-schemas /usr/share/glib-2.0/schemas/
